"database":
  "config": "mongodb://localhost:27017/"
  "db": "minos"
"global":
  "captcha":
    "comment": !!bool "false"
    "login": !!bool "false"
    "register": !!bool "false"
  "cookie_secret": !!python/unicode "2qneUccbvK7ntd5baZyX"
  "debug": !!bool "false"
  "email":
    "key": "key-xxxxx"
    "method": "none"
    "sender": "root@domain"
    "url": "https://api.mailgun.net/v3/domain"
  "imagepath": "./static/upimg"
  "init_money": !!int "1000"
  "intranet": !!bool "true"
  "invite_expire": !!int "604800"
  "register": !!python/unicode "invite"
  "site":
    "description": "\u5929\u5883\u521B\u6C47\u516C\u53F8\u5185\u90E8\u8BBA\u575B"
    "keyword": "\u5929\u5883\u521B\u6C47"
    "webname": "\u5929\u5883\u521b\u6c47"
"session":
  "db": !!int "1"
  "host": "localhost"
  "port": !!int "6379"
